<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController::index' => ['privates', '.service_locator.PeS.Fgc', 'get_ServiceLocator_PeS_FgcService.php', true],
    'App\\Controller\\ProductController::show' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\UserController::delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::edit' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::index' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\UserController::show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController:index' => ['privates', '.service_locator.PeS.Fgc', 'get_ServiceLocator_PeS_FgcService.php', true],
    'App\\Controller\\ProductController:show' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\UserController:delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:edit' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:index' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\UserController:show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
