<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCsdhBJT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCsdhBJT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCsdhBJT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCsdhBJT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCsdhBJT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CsdhBJT',
    'container.build_id' => '811e2adf',
    'container.build_time' => 1554363972,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCsdhBJT');
